/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function LightPole(props) {
  const { nodes, materials } = useGLTF("glb/Light_Pole.glb");
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI, 0, -Math.PI]} scale={[-0.44, -5.94, -0.44]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube_1.geometry}
          material={materials.Material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube_2.geometry}
          material={materials.Glow}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/glb/Light_Pole.glb");


